[package]
name = "jwt_validate"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "0.19.0", features = ['std'], default-features = false }
oidc_validate = { path = "../../oidc_validate/"}
alloy-sol-types = "0.3.2"
alloy-primitives = "0.3.3"
hex = "0.4.3"